config/routes.rb
Rails.application.routes.draw do
  resources :interviewers
  resources :interviewees
  resources :interviews
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'interviews#index'
end

app/models/interviewee.rb
class Interviewee < ApplicationRecord
    has_one_attached :resume
    def resume_present?
        if !resume.blank? 
            return 'yes'
        else
            return 'no'
        end
    end
end

app/controllers/interviewees_controller.rb
class IntervieweesController < ApplicationController
  before_action :set_interviewee, only: [:show, :edit, :update, :destroy]

  # GET /interviewees
  # GET /interviewees.json
  def index
    @interviewees = Interviewee.all
  end

  # GET /interviewees/1
  # GET /interviewees/1.json
  def show
  end

  # GET /interviewees/new
  def new
    @interviewee = Interviewee.new
  end

  # GET /interviewees/1/edit
  def edit
  end

  # POST /interviewees
  # POST /interviewees.json
  def create
    @interviewee = Interviewee.new(interviewee_params)

    respond_to do |format|
      if @interviewee.save
        format.html { redirect_to @interviewee, notice: 'Interviewee was successfully created.' }
        format.json { render :show, status: :created, location: @interviewee }
      else
        format.html { render :new }
        format.json { render json: @interviewee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interviewees/1
  # PATCH/PUT /interviewees/1.json
  def update
    respond_to do |format|
      if @interviewee.update(interviewee_params)
        format.html { redirect_to @interviewee, notice: 'Interviewee was successfully updated.' }
        format.json { render :show, status: :ok, location: @interviewee }
      else
        format.html { render :edit }
        format.json { render json: @interviewee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interviewees/1
  # DELETE /interviewees/1.json
  def destroy
    @interviewee.destroy
    respond_to do |format|
      format.html { redirect_to interviewees_url, notice: 'Interviewee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interviewee
      @interviewee = Interviewee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def interviewee_params
      params.require(:interviewee).permit(:email, :resume)
    end
end

app/helpers/interviewee_helper.rb
module IntervieweeHelper
end

app/helpers/interviewees_helper.rb
module IntervieweesHelper
end

app/views/interviewees/_form.html.erb
<%= form_with(model: interviewee, local: true) do |form| %>
  <% if interviewee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(interviewee.errors.count, "error") %> prohibited this interviewee from being saved:</h2>

      <ul>
        <% interviewee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

<div class="field">
    <%= form.label :resume_s %>
    <%= form.file_field :resume %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/interviewees/edit.html.erb
<h1>Editing Interviewee</h1>

<%= render 'form', interviewee: @interviewee %>

<%= link_to 'Show', @interviewee %> |
<%= link_to 'Back', interviewees_path %>

app/views/interviewees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interviewees</h1>

<table>
  <thead>
    <tr>
    <th>ID</th>
      <th>Email</th>
      <th>Resume</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interviewees.each do |interviewee| %>
      <tr>
      <td><%= interviewee.id %></td>
        <td><%= interviewee.email %></td>
        <td><%= interviewee.resume_present? %></td>
        <td><%= link_to 'Show', interviewee %></td>
        <td><%= link_to 'Edit', edit_interviewee_path(interviewee) %></td>
        <td><%= link_to 'Destroy', interviewee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Interviewee', new_interviewee_path %>

app/views/interviewees/new.html.erb
<h1>New Interviewee</h1>

<%= render 'form', interviewee: @interviewee %>

<%= link_to 'Back', interviewees_path %>

app/views/interviewees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @interviewee.email %>
<%# <%= image_tag(@interviewee.resume.image_url) %> %>
  <%# <iframe src=<%= @interviewee.resume %> > 
  <%# </iframe> %> %>
</p>

<%= link_to 'Edit', edit_interviewee_path(@interviewee) %> |
<%= link_to 'Back', interviewees_path %>