config/routes.rb
Rails.application.routes.draw do
  resources :interviewers
  resources :interviewees
  resources :interviews
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'interviews#index'
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :set_interview, only: [:show, :edit, :update, :destroy]

  # GET /interviews
  # GET /interviews.json
  def index
    @interviews = Interview.all.order(:start_time)
  end

  # GET /interviews/1
  # GET /interviews/1.json
  def show
  end

  # GET /interviews/new
  def new
    @interview = Interview.new
  end

  # GET /interviews/1/edit
  def edit
  end

  # POST /interviews
  # POST /interviews.json
  def create
    interviewer_id = params[:interview][:interviewer_id]
    interviewee_id = params[:interview][:interviewee_id]
    start_time, end_time = time_conversion(params)
    result, reason = Interview.participants_available(start_time, end_time, interviewer_id, interviewee_id)
    @interview = Interview.new(interview_params)
    if(result == true)
      respond_to do |format|
        if @interview.save
          format.html { redirect_to @interview, notice: 'Interview was successfully created.' }
          format.json { render :show, status: :created, location: @interview }
        else
          format.html { render :new }
          format.json { render json: @interview.errors, status: :unprocessable_entity }
        end
      end
    elsif result==false
      respond_to do |format|
        @interview.errors.add(message: reason.to_s) 
        format.html {  render :new }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interviews/1
  # PATCH/PUT /interviews/1.json
  def update
    interviewer_id = params[:interview][:interviewer_id]
    interviewee_id = params[:interview][:interviewee_id]
    start_time, end_time = time_conversion(params)
    result, reason = Interview.participants_available(start_time, end_time, interviewer_id, interviewee_id)
    if(result == true)
      respond_to do |format|
        if @interview.update(interview_params)
          format.html { redirect_to @interview, notice: 'Interview was successfully updated.' }
          format.json { render :show, status: :ok, location: @interview }
        else
          format.html { render :edit }
          format.json { render json: @interview.errors, status: :unprocessable_entity }
        end
      end
    elsif result==false
      logger.info reason
      respond_to do |format|
        @interview.errors.add(message: reason.to_s) 
        format.html { render :edit }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interviews/1
  # DELETE /interviews/1.json
  def destroy
    @interview.destroy
    respond_to do |format|
      format.html { redirect_to interviews_url, notice: 'Interview was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interview
      @interview = Interview.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def interview_params
      params.require(:interview).permit(:title, :start_time, :end_time, :interviewer_id, :interviewee_id) 
    end

    def time_conversion(params)
      start = DateTime.new(params[:interview]["start_time(1i)"].to_i, 
      params[:interview]["start_time(2i)"].to_i,
      params[:interview]["start_time(3i)"].to_i,
      params[:interview]["start_time(4i)"].to_i,
      params[:interview]["start_time(5i)"].to_i)
      close = DateTime.new(params[:interview]["end_time(1i)"].to_i, 
      params[:interview]["end_time(2i)"].to_i,
      params[:interview]["end_time(3i)"].to_i,
      params[:interview]["end_time(4i)"].to_i,
      params[:interview]["end_time(5i)"].to_i)
      return start, close
    end
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/views/interviews/_form.html.erb
<%= form_with(model: interview, local: true) do |form| %>
  <% if interview.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(interview.errors.count, "error") %> prohibited this interview from being saved:</h2>

      <ul>
        <% interview.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :interviewer_id %>
    <%= form.number_field :interviewer_id%>
  </div>
  <div class="field">
    <%= form.label :interviewee_id %>
    <%= form.number_field :interviewee_id%>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/interviews/edit.html.erb
<h1>Editing Interview</h1>

<%= render 'form', interview: @interview %>

<%= link_to 'Show', @interview %> |
<%= link_to 'Back', interviews_path %>

app/views/interviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interviews</h1>

<%# <%= week_calendar  events: @interviews do |date, interviews| %>
<%= month_calendar events: @interviews do |date, interviews| %> 
  <%= date %>

  <% interviews.each do |interview| %>
    <div>
      <%=  link_to interview.title, interview %>
    </div>
  <% end %>
<% end %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Interviewer id </th>
      <th>Interviewee id </th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interviews.each do |interview| %>
      <tr>
        <td><%= interview.title %></td>
        <td><%= interview.interviewer_id %></td>
        <td><%= interview.interviewee_id %></td>
        <td><%= interview.start_time %></td>
        <td><%= interview.end_time %></td>
        <td><%= link_to 'Show', interview %></td>
        <td><%= link_to 'Edit', edit_interview_path(interview) %></td>
        <td><%= link_to 'Destroy', interview, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Interview', new_interview_path %>

app/views/interviews/new.html.erb
<h1>New Interview</h1>

<%= render 'form', interview: @interview %>

<%= link_to 'Back', interviews_path %>

app/views/interviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @interview.title %>
</p>

<%# <p>
  <strong>Participants email:</strong>
  <%= @interview.participants_email %>
<%# </p> %> %>
<p>
<%= @interview.interviewer_id %></p>
        <p><%= @interview.interviewee_id %></p>
<p>
  <strong>Start time:</strong>
  <%= @interview.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @interview.end_time %>
</p>

<%= link_to 'Edit', edit_interview_path(@interview) %> |
<%= link_to 'Back', interviews_path %>