config/routes.rb
Rails.application.routes.draw do
  resources :interviewers
  resources :interviewees
  resources :interviews
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'interviews#index'
end

app/models/interviewer.rb
class Interviewer < ApplicationRecord
end

app/controllers/interviewers_controller.rb
class InterviewersController < ApplicationController
  before_action :set_interviewer, only: [:show, :edit, :update, :destroy]

  # GET /interviewers
  # GET /interviewers.json
  def index
    @interviewers = Interviewer.all
  end

  # GET /interviewers/1
  # GET /interviewers/1.json
  def show
  end

  # GET /interviewers/new
  def new
    @interviewer = Interviewer.new
  end

  # GET /interviewers/1/edit
  def edit
  end

  # POST /interviewers
  # POST /interviewers.json
  def create
    @interviewer = Interviewer.new(interviewer_params)

    respond_to do |format|
      if @interviewer.save
        format.html { redirect_to @interviewer, notice: 'Interviewer was successfully created.' }
        format.json { render :show, status: :created, location: @interviewer }
      else
        format.html { render :new }
        format.json { render json: @interviewer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interviewers/1
  # PATCH/PUT /interviewers/1.json
  def update
    respond_to do |format|
      if @interviewer.update(interviewer_params)
        format.html { redirect_to @interviewer, notice: 'Interviewer was successfully updated.' }
        format.json { render :show, status: :ok, location: @interviewer }
      else
        format.html { render :edit }
        format.json { render json: @interviewer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interviewers/1
  # DELETE /interviewers/1.json
  def destroy
    @interviewer.destroy
    respond_to do |format|
      format.html { redirect_to interviewers_url, notice: 'Interviewer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interviewer
      @interviewer = Interviewer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def interviewer_params
      params.require(:interviewer).permit(:email)
    end
end

app/helpers/interviewer_helper.rb
module InterviewerHelper
end

app/helpers/interviewers_helper.rb
module InterviewersHelper
end

app/views/interviewers/_form.html.erb
<%= form_with(model: interviewer, local: true) do |form| %>
  <% if interviewer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(interviewer.errors.count, "error") %> prohibited this interviewer from being saved:</h2>

      <ul>
        <% interviewer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/interviewers/edit.html.erb
<h1>Editing Interviewer</h1>

<%= render 'form', interviewer: @interviewer %>

<%= link_to 'Show', @interviewer %> |
<%= link_to 'Back', interviewers_path %>

app/views/interviewers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interviewers</h1>

<table>
  <thead>
    <tr>
    <th>ID</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interviewers.each do |interviewer| %>
      <tr>
        <td><%= interviewer.id %></td>
        <td><%= interviewer.email %></td>
        <td><%= link_to 'Show', interviewer %></td>
        <td><%= link_to 'Edit', edit_interviewer_path(interviewer) %></td>
        <td><%= link_to 'Destroy', interviewer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Interviewer', new_interviewer_path %>

app/views/interviewers/new.html.erb
<h1>New Interviewer</h1>

<%= render 'form', interviewer: @interviewer %>

<%= link_to 'Back', interviewers_path %>

app/views/interviewers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @interviewer.email %>
</p>

<%= link_to 'Edit', edit_interviewer_path(@interviewer) %> |
<%= link_to 'Back', interviewers_path %>